plugins {
    id "com.android.application"
}

android {
    namespace "com.jev.mobileagent"
    compileSdk 35

    defaultConfig {
        applicationId "com.jev.mobileagent"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
